/**
 * ModIQ — Source Layout Data
 *
 * Canonical model list for Lights of Elm Ridge sequences.
 * This is the "source" side of the mapping — what our sequences use.
 * Extracted from our xlights_rgbeffects.xml.
 */

import type { ParsedModel } from "./parser";
import { getSequenceModelList, isModelInSequence } from "./xsq-parser";

export interface SourceModel {
  name: string;
  type: string;
  displayAs: string;
  pixelCount: number;
  zone: string;
  posX: number;
  posY: number;
  isGroup: boolean;
  submodels: string[];
  memberModels?: string[]; // For groups: names of models in this group
}

/**
 * Zone assignment based on normalized position.
 * Divides the layout into a 3x3 grid.
 */
function assignZone(normX: number, normY: number): string {
  const col = normX < 0.33 ? "left" : normX < 0.66 ? "center" : "right";
  const row = normY > 0.66 ? "high" : normY > 0.33 ? "mid" : "low";
  return `${row}-${col}`;
}

/**
 * Our canonical source models — the models used across all
 * Lights of Elm Ridge sequences. Each sequence uses a subset of these.
 *
 * These come directly from our xlights_rgbeffects.xml (152 models).
 */
export const SOURCE_MODELS: SourceModel[] = [
  // ── Spinners ────────────────────────────────────────────
  {
    name: "Spinner - Showstopper 1",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 1529,
    zone: "high-left",
    posX: 0.2,
    posY: 0.85,
    isGroup: false,
    submodels: [
      "01 Cascading Arches",
      "02 Cascading Arches-Odd",
      "03 Cascading Arches-Even",
      "04 Circles (V)",
      "05 Circles-Odd (V)",
      "06 Circles-Even (V)",
      "07 Cascading Petal",
      "08 Big Petals",
      "09 Big Petals- Odd",
      "10 Big Petals-Even",
      "13 All Rings",
      "14 Trophies",
      "15 Spinners - All",
      "16 Spinners - Long",
      "17 Spinners - Short",
      "18 Swirl Right",
      "19 Swirl Left",
      "20 Arrows",
      "22 Half Willow",
      "23 Fireworks",
      "25 Snowflake",
      "27 Angle Spinner Left",
      "28 Angle Spinner Right",
      "29 Swirl and a Circle",
      "31 Short Angle Spinner",
      "32 Three-Quarters Circle",
      "33 Outer Swirl Left",
      "34 Outer Swirl Right",
      "35 Outer Rings",
      "36 Spinners - Outer",
      "40 Big Umbrella",
      "41 Saucers",
      "42 Eyes",
      "47 Diamonds",
      "51 Crosses",
      "57 Starburst",
      "65 Outer Balls",
      "70 Outline",
    ],
  },
  {
    name: "Spinner - Showstopper 2",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 1529,
    zone: "high-right",
    posX: 0.8,
    posY: 0.85,
    isGroup: false,
    submodels: [
      "01 Cascading Arches",
      "02 Cascading Arches-Odd",
      "03 Cascading Arches-Even",
      "04 Circles (V)",
      "05 Circles-Odd (V)",
      "06 Circles-Even (V)",
      "08 Big Petals",
      "09 Big Petals- Odd",
      "10 Big Petals-Even",
      "13 All Rings",
      "14 Trophies",
      "15 Spinners - All",
      "16 Spinners - Long",
      "17 Spinners - Short",
      "18 Swirl Right",
      "19 Swirl Left",
      "20 Arrows",
      "22 Half Willow",
      "23 Fireworks",
      "25 Snowflake",
      "27 Angle Spinner Left",
      "28 Angle Spinner Right",
      "29 Swirl and a Circle",
      "31 Short Angle Spinner",
      "32 Three-Quarters Circle",
      "33 Outer Swirl Left",
      "34 Outer Swirl Right",
      "35 Outer Rings",
      "36 Spinners - Outer",
      "40 Big Umbrella",
      "41 Saucers",
      "42 Eyes",
      "47 Diamonds",
      "51 Crosses",
      "57 Starburst",
      "65 Outer Balls",
      "70 Outline",
    ],
  },
  {
    name: "Spinner - Showstopper 3",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 1529,
    zone: "high-center",
    posX: 0.5,
    posY: 0.85,
    isGroup: false,
    submodels: [
      "01 Cascading Arches",
      "02 Cascading Arches-Odd",
      "03 Cascading Arches-Even",
      "04 Circles (V)",
      "05 Circles-Odd (V)",
      "06 Circles-Even (V)",
      "08 Big Petals",
      "09 Big Petals- Odd",
      "10 Big Petals-Even",
      "13 All Rings",
      "14 Trophies",
      "15 Spinners - All",
      "16 Spinners - Long",
      "17 Spinners - Short",
      "18 Swirl Right",
      "19 Swirl Left",
      "20 Arrows",
      "22 Half Willow",
      "23 Fireworks",
      "25 Snowflake",
      "27 Angle Spinner Left",
      "28 Angle Spinner Right",
      "29 Swirl and a Circle",
      "31 Short Angle Spinner",
      "32 Three-Quarters Circle",
      "33 Outer Swirl Left",
      "34 Outer Swirl Right",
      "35 Outer Rings",
      "36 Spinners - Outer",
      "40 Big Umbrella",
      "41 Saucers",
      "42 Eyes",
      "47 Diamonds",
      "51 Crosses",
      "57 Starburst",
      "65 Outer Balls",
      "70 Outline",
    ],
  },
  {
    name: "Spinner - Overlord",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 1529,
    zone: "high-center",
    posX: 0.5,
    posY: 0.9,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Spinner - Fuzion",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 800,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Spinner - Rosa Grande",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 600,
    zone: "high-center",
    posX: 0.55,
    posY: 0.8,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Spinner - Click Click Boom",
    type: "Spinner",
    displayAs: "Custom",
    pixelCount: 400,
    zone: "high-center",
    posX: 0.5,
    posY: 0.75,
    isGroup: false,
    submodels: [],
  },

  // ── Mega Tree ──────────────────────────────────────────
  {
    name: "Mega Tree",
    type: "Mega Tree",
    displayAs: "Tree 180",
    pixelCount: 6400,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.5,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Star - Treetopper",
    type: "Star",
    displayAs: "Custom",
    pixelCount: 100,
    zone: "high-center",
    posX: 0.5,
    posY: 0.95,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Star - AC Tree",
    type: "Star",
    displayAs: "Custom",
    pixelCount: 50,
    zone: "high-center",
    posX: 0.5,
    posY: 0.92,
    isGroup: false,
    submodels: [],
  },

  // ── Matrix ─────────────────────────────────────────────
  {
    name: "Matrix",
    type: "Matrix",
    displayAs: "Horiz Matrix",
    pixelCount: 7140,
    zone: "mid-left",
    posX: 0.15,
    posY: 0.5,
    isGroup: false,
    submodels: [],
  },

  // ── Floods ─────────────────────────────────────────────
  {
    name: "Floods 1",
    type: "Flood",
    displayAs: "Single Line",
    pixelCount: 8,
    zone: "low-center",
    posX: 0.3,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Floods 2",
    type: "Flood",
    displayAs: "Single Line",
    pixelCount: 8,
    zone: "low-center",
    posX: 0.4,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Floods 3",
    type: "Flood",
    displayAs: "Single Line",
    pixelCount: 8,
    zone: "low-center",
    posX: 0.5,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Floods 4",
    type: "Flood",
    displayAs: "Single Line",
    pixelCount: 8,
    zone: "low-center",
    posX: 0.6,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },

  // ── Pixel Forest ───────────────────────────────────────
  {
    name: "Pixel Forest",
    type: "Pixel Forest",
    displayAs: "Cube",
    pixelCount: 500,
    zone: "low-left",
    posX: 0.1,
    posY: 0.2,
    isGroup: false,
    submodels: ["Pixel Forest - Odds - GRP", "Pixel Forest - Evens - GRP"],
  },
  {
    name: "Pixel Forest-2",
    type: "Pixel Forest",
    displayAs: "Cube",
    pixelCount: 500,
    zone: "low-left",
    posX: 0.15,
    posY: 0.2,
    isGroup: false,
    submodels: ["Pixel Forest - Odds - GRP", "Pixel Forest - Evens - GRP"],
  },
  {
    name: "Pixel Forest-Tall",
    type: "Pixel Forest",
    displayAs: "Cube",
    pixelCount: 500,
    zone: "low-left",
    posX: 0.12,
    posY: 0.25,
    isGroup: false,
    submodels: ["Pixel Forest - Odds - GRP", "Pixel Forest - Evens - GRP"],
  },

  // ── Windows ────────────────────────────────────────────
  {
    name: "Window - Avery",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "mid-center",
    posX: 0.4,
    posY: 0.6,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Window - Ellis",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "mid-center",
    posX: 0.45,
    posY: 0.6,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Window - Garage",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "mid-left",
    posX: 0.25,
    posY: 0.55,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Window - Office",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "mid-right",
    posX: 0.65,
    posY: 0.6,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Window - Guest",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "mid-right",
    posX: 0.7,
    posY: 0.6,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Window - Tower",
    type: "Window",
    displayAs: "Window Frame",
    pixelCount: 100,
    zone: "high-center",
    posX: 0.5,
    posY: 0.7,
    isGroup: false,
    submodels: [],
  },

  // ── Eaves (Roofline) — real names from xsq ───────────
  ...(
    [
      "Eave 1- Office Left",
      "Eave 2 - Office Peak 1",
      "Eave 3 - Office Peak 2",
      "Eave 4 - Office Right",
      "Eave 5 - Entrance Arch",
      "Eave 6 - Tower Left",
      "Eave 7 - Tower Peak 1",
      "Eave 8 - Tower Peak 2",
      "Eave 9 - Upper Tower Right",
      "Eave 10 - Lower Tower Forward",
      "Eave 11 - Lower Tower Right",
      "Eave 12 - Avery Eave",
      "Eave 13 - Avery Right",
      "Eave 14 - Ellis Eave",
      "Eave 15 - Ellis Right",
      "Eave 16 - Guest Left",
      "Eave 17 - Guest Eave",
      "Eave 18 - Guest Right",
      "Eave 19 - Guest Bath",
      "Eave 20 - Guest Bath Right",
      "Eave 21 - Garage 1",
      "Eave 22 - Garage Left",
      "Eave 23 - Garage Peak 1",
      "Eave 24 - Garage Peak 2",
      "Eave 25 - Garage Right",
      "Eave 26 - Garage 2",
    ] as const
  ).map((name, i) => ({
    name,
    type: name.includes("Entrance Arch") ? "Arch" : "Roofline",
    displayAs: name.includes("Entrance Arch")
      ? "Arches"
      : ("Single Line" as string),
    pixelCount: name.includes("Entrance Arch") ? 150 : 75,
    zone: "high-center" as const,
    posX: 0.1 + (i / 26) * 0.8,
    posY: 0.7 + (i % 3) * 0.05,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Vertical Lines — real names from xsq ─────────────
  ...(
    [
      "Vert 1 - Office 1",
      "Vert 2 - Office 2",
      "Vert 3 - Tower 1",
      "Vert 4 - Entrance 1",
      "Vert 5 - Entrance 2",
      "Vert 6 - Tower 2",
      "Vert 7 - Dining",
      "Vert 8 - Avery",
      "Vert 9 - Guest 1",
      "Vert 10 - Guest 2",
      "Vert 11 - Ellis",
      "Vert 12 - Guest Bath",
      "Vert 13 - Garage 1",
      "Vert 14 - Garage 2",
      "Vert 15 - Garage 3",
    ] as const
  ).map((name, i) => ({
    name,
    type: "Line",
    displayAs: "Single Line" as string,
    pixelCount: 50,
    zone: "mid-center" as const,
    posX: 0.2 + (i / 15) * 0.6,
    posY: 0.65,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Arches ─────────────────────────────────────────────
  ...Array.from({ length: 8 }, (_, i) => ({
    name: `Arch ${i + 1}`,
    type: "Arch",
    displayAs: "Custom",
    pixelCount: 150,
    zone: "low-center" as const,
    posX: 0.15 + (i / 8) * 0.7,
    posY: 0.3,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Poles ──────────────────────────────────────────────
  ...Array.from({ length: 8 }, (_, i) => ({
    name: `Pole ${i + 1}`,
    type: "Pole",
    displayAs: "Horiz Matrix",
    pixelCount: 100,
    zone: "low-center" as const,
    posX: 0.2 + (i / 8) * 0.6,
    posY: 0.25,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Spiders (Halloween) ────────────────────────────────
  ...Array.from({ length: 8 }, (_, i) => ({
    name: `Spider ${i + 1}`,
    type: "Spider",
    displayAs: "Custom",
    pixelCount: 100,
    zone: "low-center" as const,
    posX: 0.15 + (i / 8) * 0.7,
    posY: 0.15,
    isGroup: false,
    submodels: [
      "Leg1",
      "Leg2",
      "Leg3",
      "Leg4",
      "Leg5",
      "Leg6",
      "Leg7",
      "Leg8",
      "Body",
      "Eyes",
      "Mouth",
      "HourGlass",
    ],
  })),

  // ── Bats (Halloween) ───────────────────────────────────
  ...Array.from({ length: 7 }, (_, i) => ({
    name: `Bat ${i + 1}`,
    type: "Bat",
    displayAs: "Custom",
    pixelCount: 50,
    zone: "mid-center" as const,
    posX: 0.2 + (i / 7) * 0.6,
    posY: 0.55,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Tombstones (Halloween) ─────────────────────────────
  ...Array.from({ length: 4 }, (_, i) => ({
    name: `Tombstone ${i + 1}`,
    type: "Tombstone",
    displayAs: "Custom",
    pixelCount: 80,
    zone: "low-center" as const,
    posX: 0.3 + (i / 4) * 0.4,
    posY: 0.2,
    isGroup: false,
    submodels: ["Outline", "RIP"],
  })),

  ...Array.from({ length: 6 }, (_, i) => ({
    name: `Tombstone Small - ${i + 1}`,
    type: "Tombstone",
    displayAs: "Custom",
    pixelCount: 40,
    zone: "low-center" as const,
    posX: 0.25 + (i / 6) * 0.5,
    posY: 0.18,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── GE Rosa Tombs ──────────────────────────────────────
  ...Array.from({ length: 4 }, (_, i) => ({
    name: `GE Rosa Tomb ${i + 1}`,
    type: "Tombstone",
    displayAs: "Custom",
    pixelCount: 100,
    zone: "low-center" as const,
    posX: 0.35 + (i / 4) * 0.3,
    posY: 0.22,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Mini Pumpkins (Halloween) ──────────────────────────
  ...Array.from({ length: 8 }, (_, i) => ({
    name: `Pumpkin Mini ${i + 1}`,
    type: "Pumpkin",
    displayAs: "Custom",
    pixelCount: 33,
    zone: "low-center" as const,
    posX: 0.15 + (i / 8) * 0.7,
    posY: 0.1,
    isGroup: false,
    submodels: ["Outline", "Mouth", "Eyes"],
  })),

  // ── Mini Trees ─────────────────────────────────────────
  ...Array.from({ length: 6 }, (_, i) => ({
    name: `Tree - Small ${i + 1}`,
    type: "Tree",
    displayAs: "Tree 180",
    pixelCount: 100,
    zone: "low-center" as const,
    posX: 0.2 + (i / 6) * 0.6,
    posY: 0.2,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Medium Trees ───────────────────────────────────────
  {
    name: "Tree - Medium 1",
    type: "Tree",
    displayAs: "Tree 180",
    pixelCount: 200,
    zone: "low-left",
    posX: 0.25,
    posY: 0.3,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree - Medium 2",
    type: "Tree",
    displayAs: "Tree 180",
    pixelCount: 200,
    zone: "low-right",
    posX: 0.75,
    posY: 0.3,
    isGroup: false,
    submodels: [],
  },

  // ── Real Trees ─────────────────────────────────────────
  {
    name: "Tree Real 1 - Trunk",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 250,
    zone: "mid-right",
    posX: 0.7,
    posY: 0.5,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree Real 1 - Fork Left",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 200,
    zone: "mid-right",
    posX: 0.68,
    posY: 0.55,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree Real 1 - Fork Right",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 200,
    zone: "mid-right",
    posX: 0.72,
    posY: 0.55,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree Real 2",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 250,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.45,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree Real 3",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 250,
    zone: "mid-center",
    posX: 0.48,
    posY: 0.45,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tree Real 4",
    type: "Tree",
    displayAs: "Tree 360",
    pixelCount: 250,
    zone: "mid-center",
    posX: 0.52,
    posY: 0.45,
    isGroup: false,
    submodels: [],
  },

  // ── Spiral Trees ───────────────────────────────────────
  ...Array.from({ length: 8 }, (_, i) => ({
    name: `Tree - Spiral ${i + 1}`,
    type: "Spiral Tree",
    displayAs: "Tree 360",
    pixelCount: 100,
    zone: "low-right" as const,
    posX: 0.6 + (i / 8) * 0.3,
    posY: 0.2,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Fireworks / Inverted Trees ────────────────────────
  {
    name: "Firework 1",
    type: "Spiral Tree",
    displayAs: "Tree Flat",
    pixelCount: 100,
    zone: "mid-left",
    posX: 0.2,
    posY: 0.4,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Firework 2",
    type: "Spiral Tree",
    displayAs: "Tree Flat",
    pixelCount: 100,
    zone: "mid-right",
    posX: 0.8,
    posY: 0.4,
    isGroup: false,
    submodels: [],
  },

  // ── Fence Panels ───────────────────────────────────────
  ...Array.from({ length: 7 }, (_, i) => ({
    name: `Fence Panel ${i + 1}`,
    type: "Fence",
    displayAs: "Vert Matrix",
    pixelCount: 665,
    zone: "low-left" as const,
    posX: 0.05 + (i / 7) * 0.35,
    posY: 0.15,
    isGroup: false,
    submodels: [] as string[],
  })),

  // ── Singing Pumpkin ────────────────────────────────────
  {
    name: "Singing Pumpkin",
    type: "Singing Face",
    displayAs: "Custom",
    pixelCount: 200,
    zone: "low-center",
    posX: 0.5,
    posY: 0.15,
    isGroup: false,
    submodels: ["Singing Pumpkin Outline"],
  },

  // ── Tune To Signs ──────────────────────────────────────
  {
    name: "Tune-To-Matrix",
    type: "Sign",
    displayAs: "Custom",
    pixelCount: 320,
    zone: "low-right",
    posX: 0.85,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },
  {
    name: "Tune-To-Matrix-2",
    type: "Sign",
    displayAs: "Custom",
    pixelCount: 320,
    zone: "low-left",
    posX: 0.15,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },

  // ── Driveway ───────────────────────────────────────────
  {
    name: "Driveway Left",
    type: "Outline",
    displayAs: "Poly Line",
    pixelCount: 500,
    zone: "low-left",
    posX: 0.1,
    posY: 0.1,
    isGroup: false,
    submodels: [],
  },

  // ── Spider Tree Topper ─────────────────────────────────
  {
    name: "Spider - Tree Topper",
    type: "Spider",
    displayAs: "Custom",
    pixelCount: 100,
    zone: "high-center",
    posX: 0.5,
    posY: 0.95,
    isGroup: false,
    submodels: [],
  },
];

/**
 * Group models are virtual — they reference collections of individual models.
 * We list them separately because they appear in xmap files.
 */
export const SOURCE_GROUPS: SourceModel[] = [
  // ── Master Groups ─────────────────────────────────────
  {
    name: "All - Pixels - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "all",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - No Spinners - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "all",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - No Spinners No Tree - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "all",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },

  // ── House Groups ──────────────────────────────────────
  {
    name: "All - House Outlines - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.5,
    posY: 0.7,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Eaves - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.5,
    posY: 0.75,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Verts - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.65,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All House Verts - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.65,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All House Horizontals - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.5,
    posY: 0.72,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - House - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.6,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Windows - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.6,
    isGroup: true,
    submodels: [],
  },

  // ── Yard Groups ───────────────────────────────────────
  {
    name: "All - Yard - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Arches - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.3,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Poles - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.25,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Fireworks - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.4,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Mini Trees - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Trees - Real - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.45,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Pixel Forest - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-left",
    posX: 0.12,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Fence - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-left",
    posX: 0.2,
    posY: 0.15,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Spinners - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.5,
    posY: 0.85,
    isGroup: true,
    submodels: [],
  },

  // ── Halloween Groups ──────────────────────────────────
  {
    name: "All - Spiders - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.15,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Spider Legs - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.15,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Spider Hourglasses - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.15,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Bats - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.55,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Tombstones - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All Tombstone Outlines - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All Tombstone RIPs - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Tombstones GE Rosa - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.22,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Mini Pumpkins - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.1,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Mini Pumpkin Outlines - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.1,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Mini Pumpkin Eyes - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.1,
    isGroup: true,
    submodels: [],
  },

  // ── Christmas Groups ──────────────────────────────────
  {
    name: "All - Mini Stars - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Snowflakes - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Snowflakes - Small - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Presents - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.15,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Canes - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.25,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Canes - Medium - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.25,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Spiral Trees - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-right",
    posX: 0.75,
    posY: 0.2,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Flake Spokes - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },
  {
    name: "All - Flake Arms - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "mid-center",
    posX: 0.5,
    posY: 0.5,
    isGroup: true,
    submodels: [],
  },

  // ── GE Fuzion/Rosa Submodel Groups ────────────────────
  {
    name: "GE Fuzion GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion M GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Outline GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Ring GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Triangle Lg GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Arrowhead GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Feather Even GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Feather Odd GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Flower GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Ribbon Long GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Ribon Sm GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Spoke GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Stars GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Windmill Lg Even GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Windmill Lg Odd GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Spaceship Even GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },
  {
    name: "GE Fuzion Spaceship Odd GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "high-center",
    posX: 0.45,
    posY: 0.8,
    isGroup: true,
    submodels: [],
  },

  // ── Arch submodel groups ──────────────────────────────
  {
    name: "Arches - Inner - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.3,
    isGroup: true,
    submodels: [],
  },
  {
    name: "Arches - Middle - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.3,
    isGroup: true,
    submodels: [],
  },
  {
    name: "Arches - Outer - GRP",
    type: "Group",
    displayAs: "Group",
    pixelCount: 0,
    zone: "low-center",
    posX: 0.5,
    posY: 0.3,
    isGroup: true,
    submodels: [],
  },
];

/**
 * Get all source models (individual + groups) combined
 */
export function getAllSourceModels(): SourceModel[] {
  return [...SOURCE_MODELS, ...SOURCE_GROUPS];
}

/**
 * Get source models relevant to a specific sequence.
 * If we have an xsq-derived model list for the sequence, filter to only
 * include models that the sequence actually uses. Otherwise falls back
 * to returning everything.
 */
export function getSourceModelsForSequence(
  sequenceSlug: string,
): SourceModel[] {
  const allModels = getAllSourceModels();
  const sequenceModels = getSequenceModelList(sequenceSlug);

  if (!sequenceModels) {
    // No xsq data available for this sequence — return all models
    return allModels;
  }

  return allModels.filter((model) =>
    isModelInSequence(model.name, sequenceModels),
  );
}

/**
 * Convert our source layout to ParsedModel format for use with the matching engine.
 */
export function sourceModelToParsedModel(source: SourceModel): ParsedModel {
  return {
    name: source.name,
    displayAs: source.displayAs,
    type: source.type,
    pixelCount: source.pixelCount,
    parm1: 0,
    parm2: 0,
    parm3: 0,
    stringType: "RGB Nodes",
    startChannel: "",
    worldPosX: source.posX * 2000 - 1000, // scale to approximate xLights coords
    worldPosY: source.posY * 200,
    worldPosZ: 0,
    submodels: source.submodels.map((name) => ({
      name,
      type: "ranges",
      rangeData: "",
      pixelCount: 0,
    })),
    isGroup: source.isGroup,
    aliases: [],
    memberModels: source.memberModels || [],
  };
}
